HOST: localhost:3000/
MEDIA_LOCAL: false
AWS_ACCESS_KEY_ID: AKIAIQURRAMVLKCP3MZA
AWS_BUCKET: puntospoint-media-local
AWS_SECRET_ACCESS_KEY: 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
BUNDLE_WITHOUT: development test darwin
FOG_DIRECTORY:
FOG_PROVIDER: AWS