HOST: YOUR_HOST
AWS_ACCESS_KEY_ID: YOUR_AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY: YOUR_AWS_SECRET_ACCESS_KEY
# Media bucket - paperclip
AWS_BUCKET: YOUR_AWS_BUCKET 
# Assets bucket
FOG_DIRECTORY: YOUR_FOG_DIRECTORY
FOG_PROVIDER: AWS
BUNDLE_WITHOUT: development test darwin
ECO_BILLING_DAY: 1
ECO_BILLING_INVOICE_HOUR: 4